# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: moya
talosVersion: v1.9.0-beta.1
kubernetesVersion: v1.32.0
endpoint: https://192.168.174.210:6443
domain: cluster.local
allowSchedulingOnMasters: true
allowSchedulingOnControlPlanes: true
additionalMachineCertSans:
  - 192.168.174.210
additionalApiServerCertSans:
  - 192.168.174.210
  - moya.lemon.steicke.me
clusterPodNets:
  - 10.244.0.0/16
  - 2403:580d:885c:fe00::/56
clusterSvcNets:
  - 10.96.0.0/12
  - fc00:0:0:100::/108
cniConfig:
  name: none
patches:
  - |-
    - op: replace
      path: /cluster/proxy
      value:
        disabled: true
  - |-
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: true
  - |-
    - op: add
      path: /machine/kubelet/extraConfig
      value:
        featureGates:
          UserNamespacesSupport: true
          UserNamespacesPodSecurityStandards: true
  - |-
    - op: add
      path: /machine/sysctls
      value:
        user.max_user_namespaces: "11255"
  - |-
    - op: replace
      path: /machine/features/hostDNS
      value:
        enabled: false
nodes:
  - hostname: controller
    ignoreHostname: true # expects hostname etc. to be set via DHCP
    ipAddress: 192.168.174.211, 192.168.174.212, 192.168.174.213
    controlPlane: true
    machineSpec:
      mode: metal
      arch: amd64
      useUKI: true
      secureboot: true
    #installDisk: /dev/sdb
    installDiskSelector:
      type: ssd
      #busPath: /pci0000:00/*/ata1/*
      #size: ">= 200GB"
    # NodeConfigs
    nodeAnnotations:
      model: hp-elitedesk-800-g2-mini
      installerUrl: "{{ .MachineConfig.MachineInstall.InstallImage }}"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode

  - hostname: rockpi-5b
    ignoreHostname: true # expects hostname etc. to be set via DHCP
    ipAddress: 192.168.174.215
    controlPlane: false
    # https://github.com/milas/talos-sbc-rk3588
    talosImageURL: ghcr.io/milas/talos-rk3588:v1.7.4-rk3588.alpha.4-rock-5b
    machineSpec:
      mode: metal
      arch: arm64
    installDiskSelector:
      type: sd
    # NodeConfigs
    # node annotations do not appear to be a thing in talos 1.7 used by the rockpi images
    # nodeAnnotations:
    #   model: rockpi-5b
    #   installerUrl: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    patches:
      - |-
        - op: add
          path: /machine/sysfs
          value:
            devices.platform.pwm-fan.hwmon.hwmon7.pwm1: 128

  - hostname: raspberrypi-4b
    ignoreHostname: true # expects hostname etc. to be set via DHCP
    ipAddress: 192.168.174.214
    controlPlane: false
    machineSpec:
      mode: metal
      arch: arm64
    installDiskSelector:
      type: sd
    schematic:
      overlay:
        image: siderolabs/sbc-raspberrypi
        name: rpi_generic
    # NodeConfigs
    nodeAnnotations:
      model: raspberrypi-4b
      installerUrl: "{{ .MachineConfig.MachineInstall.InstallImage }}"

controlPlane:
  disableSearchDomain: true
  nodeLabels:
    isSecureBootEnabled: >-
      {{
        .MachineConfig.MachineInstall.InstallImage |
        contains "installer-secureboot"
      }}
  networkInterfaces:
    - deviceSelector:
        physical: true
      dhcp: true
      vip:
        ip: 192.168.174.210
      # vlans:
      # - vlanId: 100
      #   dhcp: true
      #   vip:
      #     ip: 192.168.175.210
  machineFiles:
    - content: "@./apiserver/auth-configuration.yaml"
      op: create
      path: /var/apiServer/auth-configuration.yaml
      permissions: 0o644
  patches:
    - |-
      - op: add
        path: /cluster/extraManifests
        value: []
      - op: add
        path: /cluster/extraManifests/-
        value: https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
      - op: add
        path: /cluster/extraManifests/-
        value: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    - |-
      - op: add
        path: /cluster/apiServer/extraVolumes
        value:
          - hostPath: /var/apiServer/
            mountPath: /etc/config
            readonly: true
      - op: add
        path: /cluster/apiServer/extraArgs
        value:
          authentication-config: /etc/config/auth-configuration.yaml
          feature-gates: UserNamespacesSupport=true,UserNamespacesPodSecurityStandards=true
worker:
  disableSearchDomain: true

  # schematic:
  #   customization:
  #     systemExtensions:
  #       officialExtensions:
  #         - siderolabs/intel-ucode
