---
clusterName: moya
talosVersion: v1.8.3
kubernetesVersion: v1.31.3
endpoint: https://192.168.174.210:6443
domain: cluster.local
allowSchedulingOnMasters: true
allowSchedulingOnControlPlanes: true
additionalMachineCertSans:
  - 192.168.174.210
additionalApiServerCertSans:
  - 192.168.174.210
  - moya.lemon.steicke.me
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none
extraManifests:
- https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
- https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
nodes:
  - hostname: controller
    ignoreHostname: true # expects hostname etc. to be set via DHCP
    ipAddress: 192.168.174.211, 192.168.174.212, 192.168.174.213
    controlPlane: true
    machineSpec:
      mode: metal
      arch: amd64
      useUKI: true
      secureboot: true
    #installDisk: /dev/sdb
    installDiskSelector:
      type: ssd
      #busPath: /pci0000:00/*/ata1/*
      #size: ">= 200GB"
    # NodeConfigs
    nodeAnnotations:
      model: hp-elitedesk-800-g2-mini
      installerUrl: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode

  - hostname: rockpi-5b
    ignoreHostname: true # expects hostname etc. to be set via DHCP
    ipAddress: 192.168.174.215
    controlPlane: false
    talosImageURL: ghcr.io/milas/talos-rk3588:v1.7.4-rk3588.alpha.4-rock-5b
    machineSpec:
      mode: metal
      arch: arm64
    installDiskSelector:
      type: sd
    # NodeConfigs
    # node annotations do not appear to be a thing in talos 1.7 used by the rockpi images
    # nodeAnnotations:
    #   model: rockpi-5b
    #   installerUrl: '{{ .MachineConfig.MachineInstall.InstallImage }}'

controlPlane:
  disableSearchDomain: true
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          rotate-server-certificates: true
  nodeLabels:
    isSecureBootEnabled: >-
      {{
        .MachineConfig.MachineInstall.InstallImage |
        contains "installer-secureboot"
      }}
  networkInterfaces:
  - deviceSelector:
      physical: true
    dhcp: true
    vip:
      ip: 192.168.174.210
    # vlans:
    # - vlanId: 100
    #   dhcp: true
    #   vip:
    #     ip: 192.168.175.210
worker:
  disableSearchDomain: true
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          rotate-server-certificates: true
  # schematic:
  #   customization:
  #     systemExtensions:
  #       officialExtensions:
  #         - siderolabs/intel-ucode